FROM jboss/wildfly

# Set admin username and password
ENV WILDFLY_USER=admin
ENV WILDFLY_PASSWORD=admin123
RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

COPY deneme2-ear/target/deneme2-ear.ear /opt/jboss/wildfly/standalone/deployments/

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]